// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/lang.runtime;
import ballerina/test;
import ballerina/time;
import ballerinax/milvus;

const decimal MILVUS_VISIBILITY_WAIT_SECONDS = 2;

isolated function waitForMilvusVisibility() {
    runtime:sleep(MILVUS_VISIBILITY_WAIT_SECONDS);
}

final string testRunSuffix = time:utcNow()[0].toString();

string collectionName = string `test_collection_${testRunSuffix}`;
string id = "10001";
final string fileName = "test.txt";
final time:Utc createdAt = time:utcNow();

VectorStore vectorStore = check new (
    serviceUrl = "http://localhost:19530",
    apiKey = "",
    config = {
        collectionName,
        chunkFieldName: "content",
        additionalFields: ["fileName", "createdAt"]
    }
);
milvus:Client milvusClient = check new (serviceUrl = "http://localhost:19530");

@test:BeforeSuite
function beforeSuite() returns error? {
    check milvusClient->createCollection({
        collectionName,
        dimension: 2
    });
}

@test:Config {
    groups: ["insert"]
}
function testInsert() returns error? {
    check vectorStore.add(entries = [
        {
            id,
            embedding: [0.1, 0.2],
            chunk: {
                'type: "text",
                content: "test",
                metadata: {
                    fileName,
                    createdAt
                }
            }
        }
    ]);
    check milvusClient->createIndex({
        collectionName,
        primaryKey: "id",
        fieldNames: ["vector"]
    });
    waitForMilvusVisibility();
}

@test:Config {
    groups: ["delete"],
    dependsOn: [testQuery]
}
function testDelete() returns error? {
    check vectorStore.delete(id);
}

@test:Config {
    groups: ["insert"]
}
function testInsertWithoutId() returns error? {
    string autoIdCollection = string `auto_id_collection_${testRunSuffix}`;
    check milvusClient->createCollection({
        collectionName: autoIdCollection,
        dimension: 2
    });

    string autoIdFileName = "auto-id.txt";
    VectorStore autoIdVectorStore = check new (
        serviceUrl = "http://localhost:19530",
        apiKey = "",
        config = {
            collectionName: autoIdCollection,
            chunkFieldName: "content",
            additionalFields: ["fileName", "createdAt"]
        }
    );

    check autoIdVectorStore.add(entries = [
        {
            embedding: [0.3, 0.4],
            chunk: {
                'type: "text",
                content: "auto-id-test",
                metadata: {
                    fileName: autoIdFileName,
                    createdAt
                }
            }
        }
    ]);
    check milvusClient->createIndex({
        collectionName: autoIdCollection,
        primaryKey: "id",
        fieldNames: ["vector"]
    });
    waitForMilvusVisibility();
}

@test:Config {
    groups: ["query"],
    dependsOn: [testInsertWithoutId]
}
function testQueryAutoGeneratedId() returns error? {
    string autoIdFileName = "auto-id.txt";
    string autoIdCollection = string `auto_id_collection_${testRunSuffix}`;

    VectorStore autoIdVectorStore = check new (
        serviceUrl = "http://localhost:19530",
        apiKey = "",
        config = {
            collectionName: autoIdCollection,
            chunkFieldName: "content",
            additionalFields: ["fileName", "createdAt"]
        }
    );
    
    ai:VectorMatch[] matches = check autoIdVectorStore.query({
        embedding: [0.3, 0.4],
        filters: {
            filters: [
                {
                    key: "fileName",
                    value: autoIdFileName,
                    operator: ai:EQUAL
                }
            ],
            condition: ai:AND
        }
    });
    test:assertTrue(matches.length() > 0,
        "expected the auto-id entry to be retrievable after insertion");
    test:assertNotEquals(matches[0].id, "",
        "expected the vector store to assign a non-empty id when id was omitted");
    test:assertEquals(matches[0].chunk.metadata?.fileName, autoIdFileName);
}

@test:Config {
    groups: ["query"],
    dependsOn: [testInsert]
}
function testQuery() returns error? {
    ai:VectorMatch[] matches = check vectorStore.query({
        embedding: [0.1, 0.2],
        filters: {
            filters: [
                {
                    key: "fileName",
                    value: fileName,
                    operator: ai:EQUAL
                },
                {
                    key: "createdAt",
                    value: createdAt,
                    operator: ai:EQUAL
                }
            ],
            condition: ai:AND
        }
    });
    if matches.length() > 0 {
        test:assertEquals(matches[0].id, id);
        test:assertEquals(matches[0].chunk.metadata?.fileName, fileName);
        test:assertEquals(matches[0].chunk.metadata?.createdAt, createdAt);
    } else {
        test:assertFail("expected to retrieve the inserted entry, but got no matches");
    }
}

string decimalCollection = string `decimal_metadata_collection_${testRunSuffix}`;
string decimalFileName = "decimal-bug.txt";
decimal expectedFileSize = 16541d;

@test:Config {
    groups: ["insert"]
}
function testInsertWithDecimalMetadata() returns error? {
    check milvusClient->createCollection({
        collectionName: decimalCollection,
        dimension: 2
    });
    VectorStore vs = check new (
        serviceUrl = "http://localhost:19530",
        apiKey = "",
        config = {
            collectionName: decimalCollection,
            chunkFieldName: "content"
        }
    );
    check vs.add(entries = [
        {
            id: "200001",
            embedding: [0.5, 0.6],
            chunk: {
                'type: "text",
                content: "decimal-test",
                metadata: {
                    fileName: decimalFileName,
                    fileSize: expectedFileSize
                }
            }
        }
    ]);
    check milvusClient->createIndex({
        collectionName: decimalCollection,
        primaryKey: "id",
        fieldNames: ["vector"]
    });
    waitForMilvusVisibility();
}

@test:Config {
    groups: ["query"],
    dependsOn: [testInsertWithDecimalMetadata]
}
function testQueryWithDecimalMetadata() returns error? {
    VectorStore vs = check new (
        serviceUrl = "http://localhost:19530",
        apiKey = "",
        config = {
            collectionName: decimalCollection,
            chunkFieldName: "content"
        }
    );
    ai:VectorMatch[] matches = check vs.query({
        embedding: [0.5, 0.6],
        topK: 1
    });
    test:assertTrue(matches.length() > 0,
        "expected the decimal-metadata entry to be retrievable");
    ai:Metadata? md = matches[0].chunk.metadata;
    test:assertTrue(md is ai:Metadata,
        "expected metadata to convert cleanly into ai:Metadata");
    if md is ai:Metadata {
        test:assertEquals(md.fileName, decimalFileName);
        test:assertEquals(md.fileSize, expectedFileSize,
            "decimal fileSize must round-trip as a number, not as a serialized DecimalValue object");
    }
}

// Broader regression: confirm the fix also covers values that flow through the open
// `json...` rest-type — nested objects, json arrays, decimals, floats, and booleans
// were all going through the same Java reflection path and could leak runtime types.
string mixedCollection = string `mixed_metadata_collection_${testRunSuffix}`;
string mixedFileName = "mixed.txt";

@test:Config {
    groups: ["insert"]
}
function testInsertWithMixedJsonMetadata() returns error? {
    check milvusClient->createCollection({
        collectionName: mixedCollection,
        dimension: 2
    });
    VectorStore vs = check new (
        serviceUrl = "http://localhost:19530",
        apiKey = "",
        config = {
            collectionName: mixedCollection,
            chunkFieldName: "content"
        }
    );
    check vs.add(entries = [
        {
            id: "300001",
            embedding: [0.7, 0.8],
            chunk: {
                'type: "text",
                content: "mixed-test",
                metadata: {
                    fileName: mixedFileName,
                    fileSize: 2048d,
                    index: 7,
                    "tags": <json>["alpha", "beta", "gamma"],
                    "nested": <json>{"source": "unit-test", "revision": 3},
                    "approved": true,
                    "ratio": 0.75d
                }
            }
        }
    ]);
    check milvusClient->createIndex({
        collectionName: mixedCollection,
        primaryKey: "id",
        fieldNames: ["vector"]
    });
    waitForMilvusVisibility();
}

@test:Config {
    groups: ["query"],
    dependsOn: [testInsertWithMixedJsonMetadata]
}
function testQueryWithMixedJsonMetadata() returns error? {
    VectorStore vs = check new (
        serviceUrl = "http://localhost:19530",
        apiKey = "",
        config = {
            collectionName: mixedCollection,
            chunkFieldName: "content"
        }
    );
    ai:VectorMatch[] matches = check vs.query({
        embedding: [0.7, 0.8],
        topK: 1
    });
    test:assertTrue(matches.length() > 0,
        "expected the mixed-metadata entry to be retrievable");
    ai:Metadata? md = matches[0].chunk.metadata;
    test:assertTrue(md is ai:Metadata,
        "expected mixed metadata to convert cleanly into ai:Metadata");
    if md is ai:Metadata {
        test:assertEquals(md.fileName, mixedFileName);
        test:assertEquals(md.fileSize, 2048d);
        test:assertEquals(md.index, 7);
        test:assertEquals(md["tags"], <json>["alpha", "beta", "gamma"]);
        test:assertEquals(md["nested"], <json>{"source": "unit-test", "revision": 3});
        test:assertEquals(md["approved"], true);
        test:assertEquals(md["ratio"], 0.75d);
    }
}
